/**
 * 남성 화장품 제품 데이터
 * product_profiles.csv에서 변환된 JSON 데이터
 * 25개 제품 정보 포함
 */

const PRODUCTS = [
    {
        id: 1,
        product_name: "[덱스 PICK] 오브제 내추럴 커버 파운데이션 13g (SPF50+, PA++++)",
        brand: "오브제",
        suitable_shades: ["2호", "1호"],
        suitable_concerns: [],
        suitable_skin_types: [],
        coverage_score: 3.17,
        longevity_score: 2.88,
        lightweight_score: 3.61,
        product_type: "liquid",
        ingredient_level: "저자극",
        compat_oily: 0.427,
        compat_dry: 0.727,
        compat_sensitive: 0.577,
        compat_combination: 0.577,
        review_count: 184,
        avg_rating: 5.0,
        price: 36800,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000161010"
    },
    {
        id: 2,
        product_name: "[NEW/덱스PICK] 오브제 퍼펙트 커버 쿠션 15g",
        brand: "오브제",
        suitable_shades: ["1호", "2호", "3호"],
        suitable_concerns: ["spots", "acne"],
        suitable_skin_types: ["dry", "combination"],
        coverage_score: 3.33,
        longevity_score: 2.96,
        lightweight_score: 3.79,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.918,
        compat_dry: 0.918,
        compat_sensitive: 0.768,
        compat_combination: 0.918,
        review_count: 977,
        avg_rating: 4.85,
        price: 34900,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000246705&dispCatNo=1000001000700080011&trackingCd=Cat1000001000700080011_Small&t_page=%EC%B9%B4%ED%85%8C%EA%B3%A0%EB%A6%AC%EA%B4%80&t_click=%EC%BF%A0%EC%85%98/%ED%8C%8C%EC%9A%B4%EB%8D%B0%EC%9D%B4%EC%85%98_%EC%A0%84%EC%B2%B4_%EC%98%A4%EB%B8%8C%EC%A0%9C_%EC%83%81%ED%92%88%EC%83%81%EC%84%B8&t_number=3"
    },
    {
        id: 3,
        product_name: "[맨즈파데1등] 그라펜 팁 스케치 멀티 커버 파운데이션 20ml",
        brand: "그라펜",
        suitable_shades: ["21호", "23호", "27"],
        suitable_concerns: ["spots"],
        suitable_skin_types: [],
        coverage_score: 3.14,
        longevity_score: 2.48,
        lightweight_score: 3.86,
        product_type: "liquid",
        ingredient_level: "저자극",
        compat_oily: 0.931,
        compat_dry: 0.931,
        compat_sensitive: 0.781,
        compat_combination: 0.931,
        review_count: 500,
        avg_rating: 4.96,
        price: 32000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000222827"
    },
    {
        id: 4,
        product_name: "[밀착쿠션] 정샘물 맨 슬림핏 누더 쿠션",
        brand: "정샘물",
        suitable_shades: ["01", "02", "03", "27"],
        suitable_concerns: ["spots", "whitening", "wrinkle"],
        suitable_skin_types: ["combination", "dry", "oily", "sensitive"],
        coverage_score: 3.23,
        longevity_score: 2.67,
        lightweight_score: 3.82,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.467,
        compat_dry: 0.367,
        compat_sensitive: 0.317,
        compat_combination: 0.417,
        review_count: 123,
        avg_rating: 4.84,
        price: 34000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000225422"
    },
    {
        id: 5,
        product_name: "[올인원 완벽커버] 스웨거 톤 커버 파운데이션 스틱",
        brand: "스웨거",
        suitable_shades: ["1호", "2호"],
        suitable_concerns: ["spots", "pore"],
        suitable_skin_types: ["dry"],
        coverage_score: 3.25,
        longevity_score: 3.0,
        lightweight_score: 3.76,
        product_type: "stick",
        ingredient_level: "저자극",
        compat_oily: 0.857,
        compat_dry: 0.707,
        compat_sensitive: 0.857,
        compat_combination: 0.782,
        review_count: 261,
        avg_rating: 4.93,
        price: 24900,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000213066"
    },
    {
        id: 6,
        product_name: "[착붙쿠션] 그라펜 핸섬 커버쿠션 2종 택1",
        brand: "그라펜",
        suitable_shades: ["1호", "3호"],
        suitable_concerns: ["spots"],
        suitable_skin_types: ["dry", "combination", "oily"],
        coverage_score: 3.35,
        longevity_score: 3.14,
        lightweight_score: 3.62,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.861,
        compat_dry: 0.711,
        compat_sensitive: 0.711,
        compat_combination: 0.786,
        review_count: 427,
        avg_rating: 4.72,
        price: 33900,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000129149"
    },
    {
        id: 7,
        product_name: "[피부착붙컬러] 그라펜 매치업 파운데이션 40ml",
        brand: "그라펜",
        suitable_shades: ["23", "21", "27"],
        suitable_concerns: ["acne", "spots"],
        suitable_skin_types: [],
        coverage_score: 3.28,
        longevity_score: 2.69,
        lightweight_score: 3.56,
        product_type: "liquid",
        ingredient_level: "저자극",
        compat_oily: 0.676,
        compat_dry: 0.626,
        compat_sensitive: 0.626,
        compat_combination: 0.651,
        review_count: 225,
        avg_rating: 4.76,
        price: 24000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000142173"
    },
    {
        id: 8,
        product_name: "[하루종일 착붙] 원오브뎀 드 뗑 쿠션 12g",
        brand: "원오브뎀",
        suitable_shades: ["001", "002", "2호", "1호"],
        suitable_concerns: ["spots", "pore", "acne", "redness"],
        suitable_skin_types: ["dry", "oily", "sensitive", "combination"],
        coverage_score: 3.24,
        longevity_score: 2.49,
        lightweight_score: 3.81,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.547,
        compat_dry: 0.847,
        compat_sensitive: 0.847,
        compat_combination: 0.697,
        review_count: 1168,
        avg_rating: 4.98,
        price: 32000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000206573"
    },
    {
        id: 9,
        product_name: "다슈 맨즈 멀티 커버 스틱 파운데이션 (단품/기획)",
        brand: "다슈",
        suitable_shades: ["2호", "1호", "3호"],
        suitable_concerns: ["spots", "whitening", "redness"],
        suitable_skin_types: ["dry", "oily", "combination"],
        coverage_score: 3.33,
        longevity_score: 2.0,
        lightweight_score: 4.5,
        product_type: "stick",
        ingredient_level: "저자극",
        compat_oily: 0.505,
        compat_dry: 0.455,
        compat_sensitive: 0.455,
        compat_combination: 0.480,
        review_count: 16,
        avg_rating: 4.94,
        price: 29000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000229158"
    },
    {
        id: 10,
        product_name: "다슈 맨즈 멀티 커버 스틱 파운데이션 12g 뉴트럴베이지 기획",
        brand: "다슈",
        suitable_shades: ["23", "21", "2호", "3호", "1호"],
        suitable_concerns: ["spots", "acne"],
        suitable_skin_types: [],
        coverage_score: 3.33,
        longevity_score: 2.6,
        lightweight_score: 3.6,
        product_type: "stick",
        ingredient_level: "저자극",
        compat_oily: 0.505,
        compat_dry: 0.455,
        compat_sensitive: 0.455,
        compat_combination: 0.480,
        review_count: 636,
        avg_rating: 4.78,
        price: 29000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000182290"
    },
    {
        id: 11,
        product_name: "다슈 맨즈 아쿠아 매트 비비 쿠션 (리필용)",
        brand: "다슈",
        suitable_shades: ["23호"],
        suitable_concerns: ["pore"],
        suitable_skin_types: [],
        coverage_score: 3.75,
        longevity_score: 2.0,
        lightweight_score: 3.5,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.833,
        compat_dry: 0.533,
        compat_sensitive: 0.533,
        compat_combination: 0.683,
        review_count: 22,
        avg_rating: 4.91,
        price: 18000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000143169"
    },
    {
        id: 12,
        product_name: "다슈 맨즈 아쿠아 매트 비비 쿠션 15g",
        brand: "다슈",
        suitable_shades: ["23호"],
        suitable_concerns: ["spots", "whitening", "acne"],
        suitable_skin_types: ["dry"],
        coverage_score: 3.2,
        longevity_score: 4.0,
        lightweight_score: 3.67,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.844,
        compat_dry: 0.544,
        compat_sensitive: 0.544,
        compat_combination: 0.694,
        review_count: 60,
        avg_rating: 4.58,
        price: 21000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000131803"
    },
    {
        id: 13,
        product_name: "다슈 맨즈 아쿠아 매트 비비쿠션 (본품+리필)",
        brand: "다슈",
        suitable_shades: ["23호"],
        suitable_concerns: ["acne", "wrinkle", "spots", "whitening"],
        suitable_skin_types: ["oily", "dry"],
        coverage_score: 3.0,
        longevity_score: 3.0,
        lightweight_score: 4.0,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.833,
        compat_dry: 0.533,
        compat_sensitive: 0.533,
        compat_combination: 0.683,
        review_count: 8,
        avg_rating: 4.62,
        price: 30000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000143170"
    },
    {
        id: 14,
        product_name: "두잉왓 소프트 블러링 필터 쿠션 15g",
        brand: "두잉왓",
        suitable_shades: ["1호", "2호", "3호", "4호", "21"],
        suitable_concerns: ["spots", "acne"],
        suitable_skin_types: ["dry", "combination", "oily", "sensitive"],
        coverage_score: 3.33,
        longevity_score: 2.86,
        lightweight_score: 3.65,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.762,
        compat_dry: 0.362,
        compat_sensitive: 0.262,
        compat_combination: 0.562,
        review_count: 218,
        avg_rating: 4.75,
        price: 33900,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000200388"
    },
    {
        id: 15,
        product_name: "듀이셀 트루빔 파운데이션 12g",
        brand: "듀이셀",
        suitable_shades: [],
        suitable_concerns: ["spots", "whitening", "acne", "pore"],
        suitable_skin_types: ["sensitive", "dry", "oily"],
        coverage_score: 3.17,
        longevity_score: 2.0,
        lightweight_score: 3.4,
        product_type: "liquid",
        ingredient_level: "저자극",
        compat_oily: 0.523,
        compat_dry: 0.673,
        compat_sensitive: 0.673,
        compat_combination: 0.598,
        review_count: 18,
        avg_rating: 5.0,
        price: 36000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000204825"
    },
    {
        id: 16,
        product_name: "듀이셀 트루빔 파운데이션 12g 기획(+토너패드 20매)",
        brand: "듀이셀",
        suitable_shades: ["23호"],
        suitable_concerns: ["spots", "pore", "acne"],
        suitable_skin_types: ["dry"],
        coverage_score: 3.26,
        longevity_score: 2.82,
        lightweight_score: 3.71,
        product_type: "liquid",
        ingredient_level: "저자극",
        compat_oily: 0.523,
        compat_dry: 0.673,
        compat_sensitive: 0.673,
        compat_combination: 0.598,
        review_count: 935,
        avg_rating: 4.94,
        price: 36000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000210307"
    },
    {
        id: 17,
        product_name: "라끌랑 내츄럴 커버 옴므쿠션 3종 택1",
        brand: "라끌랑",
        suitable_shades: ["2호", "27", "3호", "1호"],
        suitable_concerns: ["acne"],
        suitable_skin_types: [],
        coverage_score: 3.27,
        longevity_score: 3.31,
        lightweight_score: 3.7,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.796,
        compat_dry: 0.646,
        compat_sensitive: 0.496,
        compat_combination: 0.721,
        review_count: 413,
        avg_rating: 4.75,
        price: 35000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000130814"
    },
    {
        id: 18,
        product_name: "라끌랑 슈퍼쉴드 옴므쿠션 2종 택1",
        brand: "라끌랑",
        suitable_shades: ["2호", "1호", "27", "23"],
        suitable_concerns: ["spots", "acne"],
        suitable_skin_types: ["oily"],
        coverage_score: 3.31,
        longevity_score: 3.2,
        lightweight_score: 3.75,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.919,
        compat_dry: 0.769,
        compat_sensitive: 0.919,
        compat_combination: 0.844,
        review_count: 459,
        avg_rating: 4.71,
        price: 39000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000130798"
    },
    {
        id: 19,
        product_name: "라끌랑 올데이 파워 픽스쿠션 3종 택1",
        brand: "라끌랑",
        suitable_shades: ["2호", "1호", "3호"],
        suitable_concerns: ["spots"],
        suitable_skin_types: ["oily", "combination"],
        coverage_score: 3.19,
        longevity_score: 2.89,
        lightweight_score: 3.87,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.678,
        compat_dry: 0.778,
        compat_sensitive: 0.628,
        compat_combination: 0.728,
        review_count: 100,
        avg_rating: 4.86,
        price: 37000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000184127"
    },
    {
        id: 20,
        product_name: "비레디 블루 쿠션 4세대 15g (SPF 34 PA++)",
        brand: "비레디",
        suitable_shades: ["1호", "2호", "3호", "21", "4호"],
        suitable_concerns: ["spots", "acne"],
        suitable_skin_types: ["oily", "combination", "dry"],
        coverage_score: 3.22,
        longevity_score: 3.06,
        lightweight_score: 3.77,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.452,
        compat_dry: 0.152,
        compat_sensitive: 0.402,
        compat_combination: 0.302,
        review_count: 3302,
        avg_rating: 4.84,
        price: 32900,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000212063"
    },
    {
        id: 21,
        product_name: "비레디 블루 쿠션 4세대 리필 15g",
        brand: "비레디",
        suitable_shades: ["21", "27", "23", "2호", "3호"],
        suitable_concerns: ["acne", "spots"],
        suitable_skin_types: ["combination", "sensitive"],
        coverage_score: 3.24,
        longevity_score: 2.79,
        lightweight_score: 3.78,
        product_type: "cushion",
        ingredient_level: "저자극",
        compat_oily: 0.452,
        compat_dry: 0.152,
        compat_sensitive: 0.402,
        compat_combination: 0.302,
        review_count: 364,
        avg_rating: 4.87,
        price: 24900,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000217042"
    },
    {
        id: 22,
        product_name: "비레디 블루 파운데이션 35ml",
        brand: "비레디",
        suitable_shades: ["2호", "4호", "3호", "5호", "1호"],
        suitable_concerns: ["spots", "acne"],
        suitable_skin_types: [],
        coverage_score: 3.29,
        longevity_score: 3.04,
        lightweight_score: 3.66,
        product_type: "liquid",
        ingredient_level: "저자극",
        compat_oily: 0.389,
        compat_dry: 0.189,
        compat_sensitive: 0.439,
        compat_combination: 0.289,
        review_count: 886,
        avg_rating: 4.77,
        price: 29000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000178092"
    },
    {
        id: 23,
        product_name: "엠도씨 엔드 핏 스틱 비비 파운데이션 13g",
        brand: "엠도씨",
        suitable_shades: ["3호", "2호", "1호"],
        suitable_concerns: ["acne", "spots"],
        suitable_skin_types: ["combination", "sensitive"],
        coverage_score: 3.62,
        longevity_score: 4.0,
        lightweight_score: 4.0,
        product_type: "stick",
        ingredient_level: "저자극",
        compat_oily: 0.569,
        compat_dry: 0.869,
        compat_sensitive: 0.419,
        compat_combination: 0.719,
        review_count: 31,
        avg_rating: 4.94,
        price: 29000,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000207759"
    },
    {
        id: 24,
        product_name: "오브제 내추럴 커버 파운데이션 기획세트(+클렌징폼 50ml)",
        brand: "오브제",
        suitable_shades: ["2호", "23", "1호", "3호", "21"],
        suitable_concerns: ["spots"],
        suitable_skin_types: ["combination"],
        coverage_score: 3.24,
        longevity_score: 2.84,
        lightweight_score: 3.64,
        product_type: "liquid",
        ingredient_level: "저자극",
        compat_oily: 0.836,
        compat_dry: 0.836,
        compat_sensitive: 0.686,
        compat_combination: 0.836,
        review_count: 6518,
        avg_rating: 4.84,
        price: 36800,
        product_link: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000198001"
    }
];
